export default data = [
  {
    "Products":[
        {
        "id":1,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":5,
        "description": "Hermosa tortera Giratoria, acompañada de una deliciosa Torta de Chocolate!",
        "stock": false,
        "colors":["azul", "rosado"],
        "size":"mediana",
        "price":"$5250",
        "diameter":"18 cm",
        "type":"tortera",
        "like":120
    },
    {
        "id":2,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":4,
        "description": "Hermosa tortera unica y llena de Color!",
        "stock": false,
        "colors":["blanco","negro"],
        "size":"mediana",
        "price":"$5000",
        "diameter":"20 cm",
        "type":"tortera",
        "like":155
    },
    {
        "id":3,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":5,
        "description": "Arte Funcional para La Mesa",
        "stock": false,
        "colors":["verde", "azul"],
        "size":"mediana",
        "price":"$4350",
        "diameter":"20 cm",
        "type":"tortera",
        "like":40
    },
    {
        "id":4,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score": 5,
        "description": "Esta hermosura de Tortera se fue para La Sucursal del Cielo",
        "stock": false,
        "colors":["azul","verde"],
        "size":"grande",
        "price":"$8250",
        "diameter":"24 cm",
        "type":"tortera",
        "like":16
    },
    {
        "id":5,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":2,
        "description": "Una Pieza de arte llena de color!!",
        "stock": false,
        "colors":["verde","azul","rojo","violeta"],
        "size":"grande",
        "price":"$2560",
        "diameter":"24 cm",
        "type":"tortera",
        "like":260
    },
    {
        "id":6,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":4,
        "description": "En ella, una Ancheta donde el vino , un buen queso y las uvas fueron su compañía!",
        "stock": false,
        "colors":["verde", "negro"],
        "size":"grande",
        "price":"$7500",
        "diameter":"30 cm",
        "type":"tabla giratoria",
        "like":50
    },
    {
        "id":7,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":5,
        "description": "Esta belleza de Tabla Giratoria acompañada de una deliciosa torta de Zanahoria y Banano",
        "stock": false,
        "colors":["amarrillo", "azul"],
        "size":"grande",
        "price":"$1000",
        "diameter":"30 cm",
        "type":"tabla giratoria",
        "like":17
    },
    {
        "id":8,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":4,
        "description": "Tortas y Torteras llegando a cada rincón de Colombia",
        "stock": false,
        "colors":["verde", "azul"],
        "size":"extra grande",
        "price":"$12000",
        "diameter":"40 cm",
        "type":"tabla giratoria",
        "like":50
    },
    {
        "id":9,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":4,
        "description": "NUNCA dejes de luchar por aquello que hace latir más fuerte tu corazón. Cada vez estás más cerca de lograrlo!",
        "stock": false,
        "colors":["rojo","blanco"],
        "size":"grande",
        "price":"$3000",
        "diameter":"25 cm",
        "type":"tabla giratoria",
        "like":200
    },
    {
        "id":10,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "score":1,
        "description": "El arte utilitario es una creación artística realizada con los elementos fundamentales de composición y técnica, además de ser un objeto práctico, útil y funcional.",
        "stock": false,
        "colors":["marron","celeste"],
        "size":"extra grande",
        "price":"$6600",
        "diameter":"35 cm",
        "type":"tabla giratoria",
        "like":9
    },
    {
        "id":11,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "Somos lo que dejamos en el corazón de las personas",
        "stock": true,
        "colors":["blanco","amarrillo", "azul"],
        "size":"mediana",
        "price":"$2500",
        "diameter":"20 cm",
        "type":"tortera",
        "like":5
    },
    {
        "id":12,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "para ti esta espectacular Tortera. Para que la disfrutes y que luzcas en ella todas tus creaciones!",
        "stock": true,
        "colors":["verde","naranja","rosado","rojo"],
        "size":"mediana",
        "price":"$3500",
        "diameter":"15 cm",
        "type":"tortera",
        "like":7
    },
    {
        "id":13,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "Que a tu vida nunca le falte dulce y color!!! Torta de Banano y Chips de Chocolate",
        "stock": true,
        "colors":["azul","violeta"],
        "size":"mediana",
        "price":"$5300",
        "diameter":"15 cm",
        "type":"tortera",
        "like":18
    },
    {
        "id":14,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "La creatividad es la Inteligencia divirtiéndose",
        "stock": true,
        "colors":["celeste","azul","blanco"],
        "size":"mediana",
        "price":"$4400",
        "diameter":"18 cm",
        "type":"tortera",
        "like":25
    },
    {
        "id":15,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "El significado de la vida es encontrar tu talento. El propósito de la vida es compartirlo",
        "stock": true,
        "colors":["verde","blanco","violeta", "marron"],
        "size":"mediana",
        "price":"$4600",
        "diameter":"18 cm",
        "type":"tortera",
        "like":1
    },
    {
        "id":16,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "Una Tabla Giratoria muy especial y diferente, que realmente llama la atención de todos!",
        "stock": true,
        "colors":["gris","blanco","negro"],
        "size":"grande",
        "price":"$5000",
        "diameter":"25 cm",
        "type":"tabla giratoria",
        "like":0
    },
    {
        "id":17,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "Contigo esta linda tabla giratoria que acompaña las bellezas que preparas con tanto amor!!",
        "stock": true,
        "colors":["amarrillo","azul","blanco"],
        "size":"extra grande",
        "price":"$8000",
        "diameter":"40 cm",
        "type":"tabla giratoria",
        "like":5
    },
    {
        "id":18,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "Cómo siempre… acompañada por una Deliciosa Torta de Naranja y Amapola! 🍰🍊",
        "stock": true,
        "colors":["verde","marron","negro"],
        "size":"mediana",
        "price":"$2500",
        "diameter":"28 cm",
        "type":"tabla giratoria",
        "like":100
    },
    {
        "id":19,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "Cuando sabes a donde vas.. el Universo te abre el camino",
        "stock": true,
        "colors":["rojo","rosado","blanco","naranja"],
        "size":"mediano",
        "price":"$6000",
        "diameter":"25 cm",
        "type":"tabla giratoria",
        "like":25
    },
    {
        "id":20,
        "img_home": "https://i.ibb.co/7vg98Nn/IMG-E7916.jpg",
        "img_detail":["https://i.ibb.co/ssmqrcM/CHTK0865.jpg","https://i.ibb.co/rM2BGZ9/CKTM1435.jpg"],
        "description": "Dedícate a crear, crecer y creer",
        "stock": true,
        "colors":["azul","rojo"],
        "size":"grande",
        "price":"$5000",
        "diameter":"30 cm",
        "type":"tabla giratoria",
        "like":19
    }
  ],
      "Colors":[
      "azul",
      "rosado",
      "marron",
      "blanco",
      "verde",
      "amarrillo",
      "gris",
      "rojo",
      "negro",
      "violeta",
      "naranja"
  ],
    "dimension":{
      "size": ["mediana","grande","extragrande"],
      "radius":{
          "mediana":"15 - 20 cm",
          "grande":"21 - 30 cm",
          "extra grande":"mayor a 30 cm"
      }
    }
  }
];